# Generated by Django 4.2.13 on 2024-06-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language_svg',
            field=models.CharField(default='placeholder.svg', max_length=100),
        ),
    ]
