# Generated by Django 4.2.13 on 2024-06-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_language_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(default='placeholder.svg', max_length=100),
        ),
    ]
