# Generated by Django 4.2.13 on 2024-06-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image_project_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image_url',
            new_name='image',
        ),
    ]
