# Generated by Django 4.2.13 on 2024-06-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_languages_remove_project_language_svg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='expertise_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
