# Generated by Django 4.2.13 on 2024-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='svg',
            field=models.FileField(default='svgs/placeholder.svg', upload_to='svgs/'),
        ),
    ]
