# Generated by Django 4.2.13 on 2024-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_languages_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(related_name='images', to='projects.image'),
        ),
    ]
