# Generated by Django 4.2.13 on 2024-08-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
        migrations.AlterField(
            model_name='languages',
            name='svg',
            field=models.CharField(default='placeholder.svg', max_length=100),
        ),
    ]
