# Generated by Django 4.2.13 on 2024-08-28 09:07

from django_ckeditor_5.fields import CKEditor5Field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_images_alter_languages_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=CKEditor5Field(config_name='extends', verbose_name='Text'),
        ),
    ]
