# Generated by Django 4.2.13 on 2024-08-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
