# Generated by Django 4.2.13 on 2024-08-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_languages_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='languages',
            name='main',
        ),
    ]
