version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=host.docker.internal
    volumes:
      - .:/portfolio_yo
      - static_volume:/portfolio_yo/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=facundo-duenas-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin4788
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
